export const CATEGORY_TIRE = 'Шини'

export const EMPTY_HELPER = ' '
export const ERROR_SELECT_CATEGORY = 'Оберіть категорію'
export const ERROR_SELECT_BRAND = 'Оберіть бренд'
export const ERROR_SELECT_MODEL = 'Оберіть модель'
export const ERROR_ENTER_SIZE = 'Вкажи розмір'
export const ERROR_SPEED_INDEX = 'Індекс швидкості'
export const ERROR_LOAD_INDEX = 'Індекс навантаження'
export const ERROR_ENTER_BRAND = 'Вкажи бренд'
export const ERROR_ENTER_MODEL = 'Вкажи модель'
export const ERROR_AUTO_SUBCATEGORY = 'Вкажи підкатегорію'
